name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '⚡️ Performance'
    labels:
      - 'performance'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
category-template: '### $TITLE'
change-template: '- $TITLE — @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'api-breaking'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  ## Breaking changes
  *

  ## Merged PRs

  $CHANGES
