extension FixtureManifest {
    enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case generationTool
        case hwpVersion
        case source
        case features
        case expectations
        case expectedError
    }
}

extension FixtureExpectedError {
    enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case description
    }
}

extension FixtureExpectations {
    enum CodingKeys: String, CodingKey, CaseIterable {
        case fileProperty
        case fileLicense
        case fileHeaderRawPayloadLength
        case fileHeaderRawPayloadPrefixBytes
        case fileHeaderRawPayloadSuffixBytes
        case fileHeaderVersionRawBytes
        case fileHeaderReservedLength
        case fileHeaderReservedPrefixBytes
        case fileHeaderReservedSuffixBytes
        case documentProperties
        case compatibleDocument
        case layoutCompatibility
        case docInfoIdMappings
        case docInfoRawRecords
        case docInfoBinData
        case docInfoStyles
        case docInfoNumberings
        case docInfoBullets
        case hyperlinks
        case genShapeObjects
        case shapeControls
        case tables
        case columns
        case listControls
        case pageNumberPositions
        case sections
        case preservedControls
        case preservedControlSamples
        case fieldControls
        case otherControls
        case otherControlSamples
        case encryptVersion
        case koreaOpenLicense
        case sectionCount
        case sectionRawPayloadCount
        case sectionRawPayloadTotalByteCount
        case sectionRawPayloadPrefixBytes
        case sectionRawPayloadSuffixBytes
        case sectionParagraphCounts
        case sectionVisibleTexts
        case paragraphCount
        case allParagraphCount
        case paraTextRawPayloadCount
        case paraTextRawPayloadTotalByteCount
        case paraTextRawPayloadPrefixBytes
        case paraTextRawPayloadSuffixBytes
        case paraTextPayloadCount
        case paraTextPayloadTotalByteCount
        case paraTextPayloadPrefixBytes
        case paraTextPayloadSuffixBytes
        case paraTextControlIds
        case paraTextControlIdNames
        case paraTextControlPayloadLengths
        case paraTextControlPayloadPrefixBytes
        case paraTextControlPayloadSuffixBytes
        case paraTextControlTrailingLengths
        case paraTextControlTrailingPrefixBytes
        case paraTextControlTrailingSuffixBytes
        case paraHeaderPayloadCount
        case paraHeaderPayloadTotalByteCount
        case paraHeaderPayloadPrefixBytes
        case paraHeaderPayloadSuffixBytes
        case paraCharShapePayloadCount
        case paraCharShapePayloadTotalByteCount
        case paraCharShapePayloadPrefixBytes
        case paraCharShapePayloadSuffixBytes
        case paraLineSegPayloadCount
        case paraLineSegPayloadTotalByteCount
        case paraLineSegPayloadPrefixBytes
        case paraLineSegPayloadSuffixBytes
        case paraRangeTagCount
        case paraRangeTagPayloadTotalByteCount
        case paraRangeTags
        case paragraphUnknownChildCount
        case paragraphUnknownChildTagIds
        case paragraphUnknownChildPayloadLengths
        case paragraphUnknownChildPayloadPrefixBytes
        case paragraphUnknownChildPayloadSuffixBytes
        case paragraphUnknownNestedTagIds
        case paragraphUnknownNestedPayloadLengths
        case paragraphUnknownNestedPayloadPrefixBytes
        case paragraphUnknownNestedPayloadSuffixBytes
        case sectionUnknownRecordCount
        case sectionUnknownRecordTagIds
        case sectionUnknownRecordPayloadLengths
        case sectionUnknownRecordPayloadPrefixBytes
        case sectionUnknownRecordPayloadSuffixBytes
        case sectionUnknownChildTagIds
        case sectionUnknownChildPayloadLengths
        case sectionUnknownChildPayloadPrefixBytes
        case sectionUnknownChildPayloadSuffixBytes
        case topLevelEntryNames
        case bodyTextSectionEntryNames
        case summaryLength
        case summaryPrefixBytes
        case summarySuffixBytes
        case previewTextLength
        case previewTextRawPayloadLength
        case previewTextPrefixBytes
        case previewTextSuffixBytes
        case previewTextContains
        case previewImageLength
        case previewImageFormat
        case previewImagePrefixBytes
        case previewImageSuffixBytes
        case binaryDataCount
        case binaryDataNames
        case binaryDataEntryNames
        case binaryDataStreamIds
        case binaryDataExtensionNames
        case binaryDataPayloadLengths
        case binaryDataPayloadPrefixBytes
        case binaryDataPayloadSuffixBytes
        case binaryDataTotalByteCount
        case docInfoRawPayloadLength
        case docInfoRawPayloadPrefixBytes
        case docInfoRawPayloadSuffixBytes
        case docInfoUnknownRecordCount
        case docInfoUnknownRecordTagIds
        case docInfoUnknownRecordPayloadLengths
        case docInfoUnknownRecordPayloadPrefixBytes
        case docInfoUnknownRecordPayloadSuffixBytes
        case docInfoUnknownChildTagIds
        case docInfoUnknownChildPayloadLengths
        case docInfoUnknownChildPayloadPrefixBytes
        case docInfoUnknownChildPayloadSuffixBytes
        case docInfoRawRecordCount
        case controlCount
        case allControlCount
        case visibleTextContains
        case controlTypeCounts
        case allControlTypeCounts
    }
}
