public enum HwpCtrlId {
    // common
    case table(HwpTable)
    case shape(HwpShapeControl)
    case line(HwpShapeControl)
    case rectangle(HwpShapeControl)
    case ellipse(HwpShapeControl)
    case arc(HwpShapeControl)
    case polygon(HwpShapeControl)
    case curve(HwpShapeControl)
    case equation(HwpShapeControl)
    case equationLegacy(HwpShapeControl)
    case picture(HwpShapeControl)
    case ole(HwpShapeControl)
    case container(HwpShapeControl)
    case genShapeObject(HwpGenShapeObject)
    // other
    case section(HwpSectionDef)
    case column(HwpColumn)
    case pageNumberPosition(HwpPageNumberPosition)
    case header(HwpListControl)
    case footer(HwpListControl)
    case footnote(HwpListControl)
    case endnote(HwpListControl)
    case form(HwpOtherControl)
    case autoNumber(HwpOtherControl)
    case newNumber(HwpOtherControl)
    case pageHide(HwpOtherControl)
    case pageCT(HwpOtherControl)
    case indexmark(HwpOtherControl)
    case bookmark(HwpOtherControl)
    case overlapping(HwpOtherControl)
    case comment(HwpOtherControl)
    case hiddenComment(HwpOtherControl)
    case other(HwpOtherControl)
    /// field
    case hyperLink(HwpHyperlink)
    case memo(HwpFieldControl)
    case revision(HwpFieldControl)
    case field(HwpFieldControl)
    /// not implemented
    case notImplemented(HwpCtrlHeader)
    case unknown(HwpCtrlHeader)
}

extension HwpCtrlId: HwpPrimitive {}
