name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**.swift'

  pull_request:
    branches:
      - main
    paths:
      - '**.swift'

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["5.3"]

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -c release -v
    - name: Run tests
      run: swift test -v
